# Generated by Django 2.2.27 on 2024-12-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='user_id',
            field=models.CharField(max_length=16),
        ),
    ]
