version: '3'

services:
  sec-db:
    image: postgres
    expose:
      -  "5432"
    networks:
      - djangonetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw1234
      - POSTGRES_DB=moviegeeks
  sec-rec:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8010
    mem_limit: 8G
    cpus: "2"
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    networks:
      - djangonetwork
    links:
      - sec-db:db
    depends_on:
      - sec-db

networks:
    djangonetwork:
      driver: bridge
