version: '3'

services:
  sec-db:
    image: postgres
    expose:
      -  "5432"
    networks:
      - djangonetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw1234
      - POSTGRES_DB=moviegeeks
  
  sec-rec:
    restart: no
    build:
      context: .
      dockerfile: Dockerfile.recsys
    command: python manage.py runserver 0.0.0.0:8010
    mem_limit: 3G
    cpus: "2"
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    networks:
      - djangonetwork
    links:
      - sec-db:db
      - csp:csp
    depends_on:
      - sec-db
      - csp
  
  csp:
    build:
      context: .
      dockerfile: Dockerfile.csp
    command: python csp_server.py
    mem_limit: 5GB
    cpus: "4"
    volumes:
      - ./csp:/code
    ports:
      - "5000:5000"
    networks:
      - djangonetwork

networks:
    djangonetwork:
      driver: bridge
