# Generated by Django 2.2.27 on 2024-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20241213_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='enc_rating',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='type',
            field=models.CharField(choices=[('real', 'Real'), ('fake', 'Fake')], default='real', max_length=10),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user_id', 'movie_id'], name='analytics_r_user_id_e8e805_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['type'], name='analytics_r_type_a677d7_idx'),
        ),
    ]
